[package]
name = "jcpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jcpuinstructions = { path = "../jcpu-instructions" }

crossterm = { version = "0.25.0", event-stream = true }
